// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DemoSectionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void savingDefaultChartSettingsWorks() {
    driver.get("https://statcounter.com/");
    driver.manage().window().setSize(new Dimension(1920, 1054));
    driver.findElement(By.xpath("//li[@id=\'nav-demo\']/a")).click();
    assertTrue(driver.findElement(By.xpath("//input[@id=\'show_returningvisits\']")).isSelected());
    driver.findElement(By.xpath("//input[@id=\'show_returningvisits\']")).click();
    assertTrue(driver.findElement(By.xpath("//input[@id=\'show_uniquevisits\']")).isSelected());
    driver.findElement(By.xpath("//input[@id=\'show_uniquevisits\']")).click();
    assertTrue(driver.findElement(By.xpath("//input[@id=\'show_pageviews\']")).isSelected());
    driver.findElement(By.xpath("//input[@id=\'show_pageviews\']")).click();
    driver.findElement(By.xpath("//input[@id=\'save_as_default\']")).click();
    driver.get("https://statcounter.com/demo/summary/");
    assertFalse(driver.findElement(By.xpath("//input[@id=\'show_uniquevisits\']")).isSelected());
    assertFalse(driver.findElement(By.xpath("//input[@id=\'show_returningvisits\']")).isSelected());
    assertFalse(driver.findElement(By.xpath("//input[@id=\'show_pageviews\']")).isSelected());
    driver.findElement(By.xpath("//input[@id=\'show_pageviews\']")).click();
    driver.findElement(By.xpath("//input[@id=\'show_uniquevisits\']")).click();
    driver.findElement(By.xpath("//input[@id=\'show_returningvisits\']")).click();
    driver.findElement(By.xpath("//input[@id=\'save_as_default\']")).click();
  }
  @Test
  public void labelsOnChartWorks() {
    driver.get("https://statcounter.com/");
    driver.manage().window().setSize(new Dimension(1920, 1054));
    driver.findElement(By.xpath("//li[@id=\'nav-demo\']/a")).click();
    driver.findElement(By.cssSelector(".y:nth-child(7) > .tick:nth-child(8) > text")).click();
    driver.findElement(By.xpath("//div[@id=\'summary-chart-options-trigger\']")).click();
  }
}
